// Reads the rows out of the Express/Render database and writes SQL that loads
// them into Supabase.
//
//   node supabase/export-data.mjs --user you@example.com --owner <supabase-user-id> > data.sql
//
// The Supabase user id is the one auth.users gives you after signing up there;
// every row is written against it, so the data lands in the right account and
// under the policies rather than beside them. Nothing is written to either
// database by this script — it only prints.

import pg from 'pg';

const args = Object.fromEntries(
  process.argv.slice(2).reduce((pairs, arg, index, all) => {
    if (arg.startsWith('--')) pairs.push([arg.slice(2), all[index + 1]]);
    return pairs;
  }, [])
);

if (!args.user || !args.owner) {
  console.error('usage: node supabase/export-data.mjs --user <email> --owner <supabase user id>');
  process.exit(1);
}
if (!process.env.DATABASE_URL) {
  console.error('DATABASE_URL must point at the database being moved');
  process.exit(1);
}

const db = new pg.Client({
  connectionString: process.env.DATABASE_URL,
  ssl: process.env.DATABASE_SSL === 'true' ? { rejectUnauthorized: false } : false
});
await db.connect();

const { rows: users } = await db.query('select id, email, display_name from users where email = $1', [
  args.user
]);
if (users.length === 0) {
  console.error(`no account here for ${args.user}`);
  process.exit(1);
}
const source = users[0].id;
const owner = args.owner;

const quote = (value) => {
  if (value === null || value === undefined) return 'null';
  if (typeof value === 'number') return String(value);
  return `'${String(value).replace(/'/g, "''")}'`;
};

const out = [];
const say = (line) => out.push(line);

say('-- Generated by supabase/export-data.mjs. Review before running.');
say('begin;');

const { rows: settings } = await db.query('select key, value from settings where user_id = $1', [source]);
const asSetting = (key) => settings.find((row) => row.key === key)?.value ?? null;

say(
  `insert into public.profiles (id, display_name, monthly_budget) values (${quote(owner)}, ${quote(
    asSetting('displayName') || users[0].display_name || ''
  )}, ${Number(asSetting('monthlyBudget') || 0)})
  on conflict (id) do update set display_name = excluded.display_name, monthly_budget = excluded.monthly_budget;`
);

// Accounts keep their ids, so transactions can point at them without a lookup.
const { rows: accounts } = await db.query(
  'select id, name, opening_balance, created_at from accounts where user_id = $1',
  [source]
).catch(() => ({ rows: [] }));

for (const account of accounts) {
  say(
    `insert into public.accounts (id, user_id, name, opening_balance, created_at) values (${quote(
      account.id
    )}, ${quote(owner)}, ${quote(account.name)}, ${Number(account.opening_balance)}, ${quote(
      account.created_at.toISOString()
    )}) on conflict (id) do nothing;`
  );
}

const { rows: transactions } = await db.query(
  `select id, kind, description, amount, category, to_char(date, 'YYYY-MM-DD') as date,
          payment_method, note, source, external_ref, account_id, created_at, updated_at
   from expenses where user_id = $1 order by date`,
  [source]
);

for (const row of transactions) {
  say(
    `insert into public.transactions (id, user_id, account_id, kind, description, amount, category, date, payment_method, note, source, external_ref, created_at, updated_at) values (${[
      quote(row.id),
      quote(owner),
      quote(row.account_id),
      quote(row.kind || 'expense'),
      quote(row.description),
      Number(row.amount),
      quote(row.category),
      quote(row.date),
      quote(row.payment_method),
      quote(row.note || ''),
      quote(row.source || 'manual'),
      quote(row.external_ref),
      quote(row.created_at.toISOString()),
      quote(row.updated_at.toISOString())
    ].join(', ')}) on conflict (id) do nothing;`
  );
}

const { rows: budgets } = await db.query(
  'select category, monthly_limit from budgets where user_id = $1',
  [source]
);
for (const row of budgets) {
  say(
    `insert into public.budgets (user_id, category, monthly_limit) values (${quote(owner)}, ${quote(
      row.category
    )}, ${Number(row.monthly_limit)}) on conflict (user_id, category) do update set monthly_limit = excluded.monthly_limit;`
  );
}

const { rows: recurring } = await db.query(
  'select id, description, amount, category, day_of_month, payment_method, created_at from recurring where user_id = $1',
  [source]
);
for (const row of recurring) {
  say(
    `insert into public.recurring (id, user_id, description, amount, category, day_of_month, payment_method, created_at) values (${[
      quote(row.id),
      quote(owner),
      quote(row.description),
      Number(row.amount),
      quote(row.category),
      Number(row.day_of_month),
      quote(row.payment_method),
      quote(row.created_at.toISOString())
    ].join(', ')}) on conflict (id) do nothing;`
  );
}

const { rows: goals } = await db.query(
  'select id, name, icon, target_amount, saved_amount, created_at from goals where user_id = $1',
  [source]
).catch(() => ({ rows: [] }));
for (const row of goals) {
  say(
    `insert into public.goals (id, user_id, name, icon, target_amount, saved_amount, created_at) values (${[
      quote(row.id),
      quote(owner),
      quote(row.name),
      quote(row.icon || 'target'),
      Number(row.target_amount),
      Number(row.saved_amount),
      quote(row.created_at.toISOString())
    ].join(', ')}) on conflict (id) do nothing;`
  );
}

const { rows: contributions } = await db.query(
  'select id, goal_id, amount, created_at from goal_contributions where user_id = $1',
  [source]
).catch(() => ({ rows: [] }));
for (const row of contributions) {
  say(
    `insert into public.goal_contributions (id, goal_id, user_id, amount, created_at) values (${[
      quote(row.id),
      quote(row.goal_id),
      quote(owner),
      Number(row.amount),
      quote(row.created_at.toISOString())
    ].join(', ')}) on conflict (id) do nothing;`
  );
}

const { rows: receipts } = await db.query(
  'select count(*)::int as count from receipts where user_id = $1',
  [source]
);

say('commit;');
say('');
say(
  `-- ${transactions.length} transactions, ${accounts.length} accounts, ${budgets.length} budgets, ` +
    `${recurring.length} recurring, ${goals.length} goals, ${contributions.length} contributions.`
);
if (receipts[0].count > 0) {
  say(
    `-- ${receipts[0].count} receipt file(s) are NOT included: they are bytes in the old database` +
      ' and belong in Supabase Storage. Move them separately, or leave them behind deliberately.'
  );
}

console.log(out.join('\n'));
await db.end();
